[Variables]

; Font Variables
TextFont=Fira Sans
MediumTextFont=Fira Sans Medium
ThinFont=Fira Sans Light
MonoFont=Fira Mono

; Color Variables
LabelColor=255,255,255
ValueColor=255,255,255
BarBackColor=#LabelColor#,75
BackgroundAlpha=200
BackgroundColor=0,0,0,#BackgroundAlpha#
FrameColor=120,120,120,255
IconAlpha=200
OffLight=137,137,137,255
GreenLight=105,209,115,255
YellowLight=217,204,65,255
RedLight=230,78,78,255
BlueLight=65,154,217,255
CoralLight=244,125,67,255

; Image Variables.
ImagePath=#@#Images\
