[Variables]
; HWiNFO variables

TempUnit=°C

HWiNFODesc1=CPU Chip
HWiNFOSensorId1=0xf0008686
HWiNFOSensorInstance1=0x0
HWiNFOEntryId1=0x1000002
HWiNFOType1=CurrentValue
HWiNFOMin1=10
HWiNFOMax1=90

HWiNFODesc2=CPU Fan
HWiNFOSensorId2=0xf0008686
HWiNFOSensorInstance2=0x0
HWiNFOEntryId2=0x3000000
HWiNFOType2=CurrentValue
HWiNFOMin2=1000
HWiNFOMax2=2000

HWiNFODesc3=Motherboard
HWiNFOSensorId3=0xf0008686
HWiNFOSensorInstance3=0x0
HWiNFOEntryId3=0x1000001
HWiNFOType3=CurrentValue
HWiNFOMin3=10
HWiNFOMax3=90

HWiNFODesc4=Graphics
HWiNFOSensorId4=0xe0002000
HWiNFOSensorInstance4=0x0
HWiNFOEntryId4=0x1000000
HWiNFOType4=CurrentValue
HWiNFOMin4=10
HWiNFOMax4=90
